workflows:
  winatra-android:
    name: Build Winatra AI APK
    environment:
      groups:
        - winatra_secrets   # nanti buat group secret di Codemagic
      flutter: 3.27.4
    scripts:
      - name: Create google-services.json
        script: |
          echo "$GOOGLEJSON" > android/app/google-services.json
      - name: Inject Groq keys
        script: |
          IFS=',' read -r -a keys <<< "$GROQKEYS"
          for i in "${!keys[@]}"; do
            num=$((i+1))
            sed -i "s#BUILD_GROQ_KEY_$num#${keys[$i]}#g" android/app/src/main/kotlin/com/example/winatra_ai/WinatraService.kt
            sed -i "s#BUILD_GROQ_KEY_$num#${keys[$i]}#g" android/app/src/main/kotlin/com/example/winatra_ai/WinatraKeyboardService.kt
          done
      - name: Inject DeepSeek key
        script: |
          sed -i "s#BUILD_DEEPSEEK_KEY#$DEEPSEEKKEY#g" android/app/src/main/kotlin/com/example/winatra_ai/WinatraService.kt
          sed -i "s#BUILD_DEEPSEEK_KEY#$DEEPSEEKKEY#g" android/app/src/main/kotlin/com/example/winatra_ai/WinatraKeyboardService.kt
      - name: Build APK
        script: |
          flutter clean
          flutter pub get
          flutter build apk --release --split-per-abi
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
    publishing:
      email:
        recipients:
          - emailanda@example.com   # GANTI DENGAN EMAIL ANDA
